# Generated by Django 4.2.29 on 2026-04-02 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('GUIDANCE', 'Guidance'), ('DRAFT', 'Draft'), ('ASSESSMENT', 'Assessment')], max_length=20)),
                ('prompt_context_snapshot', models.JSONField(blank=True, default=dict)),
                ('content', models.TextField()),
                ('model_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_generated_outputs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_outputs', to=settings.AUTH_USER_MODEL)),
                ('project_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_outputs', to='indicators.projectindicator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
