# Generated by Django 5.2.12 on 2026-04-28 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_actions', '0001_initial'),
        ('frameworks', '0001_initial'),
        ('projects', '0002_accreditationproject_client_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feature', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('is_demo_mode', models.BooleanField(default=False)),
                ('indicator_code', models.CharField(blank=True, max_length=50)),
                ('is_success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frameworks.framework')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.accreditationproject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
