# Generated by Django 5.2.12 on 2026-04-29 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_actions', '0002_aiusagelog'),
        ('evidence', '0002_evidenceitem_file_label_and_more'),
        ('frameworks', '0001_initial'),
        ('indicators', '0003_indicator_ai_assistance_level_and_more'),
        ('projects', '0002_accreditationproject_client_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('SOP', 'SOP'), ('POLICY', 'Policy'), ('FORM', 'Form'), ('MINUTES', 'Minutes'), ('REPORT', 'Report'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('draft_content', models.TextField()),
                ('prompt_snapshot', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='AI', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('review_status', models.CharField(choices=[('DRAFT', 'Draft'), ('HUMAN_REVIEW_REQUIRED', 'Human Review Required'), ('HUMAN_REVIEWED', 'Human Reviewed'), ('PROMOTED_TO_EVIDENCE', 'Promoted to Evidence'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('is_advisory', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('ai_usage_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_drafts', to='ai_actions.aiusagelog')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_drafts', to='frameworks.framework')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_document_drafts', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_drafts', to='indicators.indicator')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_document_drafts', to=settings.AUTH_USER_MODEL)),
                ('parent_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='ai_actions.documentdraft')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_drafts', to='projects.accreditationproject')),
                ('project_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_drafts', to='indicators.projectindicator')),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_document_drafts', to=settings.AUTH_USER_MODEL)),
                ('promoted_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_document_drafts', to='evidence.evidenceitem')),
            ],
            options={
                'verbose_name': 'Document Draft',
                'verbose_name_plural': 'Document Drafts',
                'ordering': ['-generated_at'],
            },
        ),
    ]
