# Generated by Django 4.2.29 on 2026-05-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_indicator_ai_assistance_level_and_more'),
        ('ai_actions', '0003_documentdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdraft',
            name='draft_kind',
            field=models.CharField(choices=[('SOP', 'SOP'), ('POLICY', 'Policy'), ('CHECKLIST', 'Checklist'), ('REGISTER_TEMPLATE', 'Register template'), ('EVIDENCE_REQUIREMENT_SHEET', 'Evidence requirement sheet'), ('GAP_CLOSURE_PLAN', 'Gap closure plan')], default='POLICY', max_length=40),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='related_indicators',
            field=models.ManyToManyField(blank=True, related_name='related_document_drafts', to='indicators.indicator'),
        ),
    ]
