# Generated by Django 4.2.29 on 2026-04-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key', 'sort_order', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='mastervalue',
            constraint=models.UniqueConstraint(fields=('key', 'code'), name='unique_master_key_code'),
        ),
    ]
