# Generated by Django 4.2.29 on 2026-04-02 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('frameworks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('required_evidence_description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('POLICY', 'Policy'), ('REPORT', 'Report'), ('IMAGE', 'Image'), ('URL', 'URL'), ('OTHER', 'Other')], default='DOCUMENT', max_length=20)),
                ('document_type', models.CharField(choices=[('SOP', 'SOP'), ('POLICY', 'Policy'), ('FORM', 'Form'), ('MINUTES', 'Minutes'), ('REPORT', 'Report'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('fulfillment_guidance', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NONE', max_length=10)),
                ('recurrence_mode', models.CharField(choices=[('DIGITAL', 'Digital'), ('UPLOAD', 'Upload'), ('EITHER', 'Either')], default='EITHER', max_length=10)),
                ('minimum_required_evidence_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='frameworks.area')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='frameworks.framework')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='frameworks.standard')),
            ],
            options={
                'ordering': ['area__sort_order', 'standard__sort_order', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Under Review'), ('MET', 'Met'), ('BLOCKED', 'Blocked')], default='NOT_STARTED', max_length=20)),
                ('is_finalized', models.BooleanField(default=False)),
                ('is_met', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approve_project_indicators', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_indicators', to='indicators.indicator')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_indicators', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_project_indicators', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_indicators', to='projects.accreditationproject')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_project_indicators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project__name', 'indicator__area__sort_order', 'indicator__sort_order', 'indicator__code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIndicatorStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Under Review'), ('MET', 'Met'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('to_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Under Review'), ('MET', 'Met'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_indicator_status_changes', to=settings.AUTH_USER_MODEL)),
                ('project_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='indicators.projectindicator')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIndicatorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WORKING', 'Working'), ('REVIEW', 'Review'), ('APPROVAL', 'Approval')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_indicator_comments', to=settings.AUTH_USER_MODEL)),
                ('project_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='indicators.projectindicator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectindicator',
            constraint=models.UniqueConstraint(fields=('project', 'indicator'), name='unique_project_indicator'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.UniqueConstraint(fields=('framework', 'code'), name='unique_indicator_code_per_framework'),
        ),
    ]
