# Generated by Django 4.2.29 on 2026-04-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='evidence_reuse_policy',
            field=models.CharField(choices=[('NONE', 'None'), ('MANUAL_REVIEW', 'Manual Review'), ('AUTO_ALLOWED', 'Auto Allowed')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='reusable_template_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
