# Generated by Django 4.2.29 on 2026-04-28 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_legacy_evidence_type_codes(apps, schema_editor):
    Indicator = apps.get_model('indicators', 'Indicator')
    mapping = {
        'DOCUMENT': 'DOCUMENT_POLICY',
        'POLICY': 'DOCUMENT_POLICY',
        'REPORT': 'RECORD_REGISTER',
        'IMAGE': 'PHYSICAL_FACILITY',
        'URL': 'MANUAL_REVIEW',
        'OTHER': 'MANUAL_REVIEW',
    }
    for old_value, new_value in mapping.items():
        Indicator.objects.filter(evidence_type=old_value).update(evidence_type=new_value)


def reverse_legacy_evidence_type_codes(apps, schema_editor):
    Indicator = apps.get_model('indicators', 'Indicator')
    mapping = {
        'DOCUMENT_POLICY': 'DOCUMENT',
        'RECORD_REGISTER': 'REPORT',
        'PHYSICAL_FACILITY': 'IMAGE',
        'LICENSE_CERTIFICATE': 'OTHER',
        'STAFF_TRAINING': 'OTHER',
        'PROCESS_WORKFLOW': 'OTHER',
        'AUDIT_QUALITY': 'REPORT',
        'MIXED_EVIDENCE': 'OTHER',
        'MANUAL_REVIEW': 'OTHER',
    }
    for old_value, new_value in mapping.items():
        Indicator.objects.filter(evidence_type=old_value).update(evidence_type=new_value)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0002_indicator_evidence_reuse_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='ai_assistance_level',
            field=models.CharField(blank=True, choices=[('FULL_AI', 'Full AI'), ('PARTIAL_AI', 'Partial AI'), ('NO_AI', 'No AI')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='classification_confidence',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='indicator',
            name='classification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='classification_review_status',
            field=models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('AI_SUGGESTED', 'AI Suggested'), ('HUMAN_REVIEWED', 'Human Reviewed'), ('MANUALLY_CHANGED', 'Manually Changed'), ('NEEDS_REVIEW', 'Needs Review')], default='UNCLASSIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='classification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='classification_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_indicator_classifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicator',
            name='classification_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='classified_by_ai_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='evidence_frequency',
            field=models.CharField(blank=True, choices=[('ONE_TIME', 'One-time'), ('RECURRING', 'Recurring'), ('EVENT_BASED', 'Event-based')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='primary_action_required',
            field=models.CharField(blank=True, choices=[('GENERATE_DOCUMENT', 'Generate Document'), ('COLLECT_RECORD', 'Collect Record'), ('UPLOAD_PHOTO', 'Upload Photo'), ('ARRANGE_PHYSICAL_COMPLIANCE', 'Arrange Physical Compliance'), ('OBTAIN_CERTIFICATE', 'Obtain Certificate'), ('TRAIN_STAFF', 'Train Staff'), ('MAINTAIN_LOG', 'Maintain Log'), ('REVIEW_EXISTING_EVIDENCE', 'Review Existing Evidence'), ('MANUAL_DECISION', 'Manual Decision')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='evidence_type',
            field=models.CharField(choices=[('DOCUMENT_POLICY', 'Document / Policy'), ('RECORD_REGISTER', 'Record / Register'), ('PHYSICAL_FACILITY', 'Physical / Facility'), ('LICENSE_CERTIFICATE', 'License / Certificate'), ('STAFF_TRAINING', 'Staff / Training'), ('PROCESS_WORKFLOW', 'Process / Workflow'), ('AUDIT_QUALITY', 'Audit / Quality'), ('MIXED_EVIDENCE', 'Mixed Evidence'), ('MANUAL_REVIEW', 'Manual Review Needed')], default='MANUAL_REVIEW', max_length=32),
        ),
        migrations.RunPython(migrate_legacy_evidence_type_codes, reverse_legacy_evidence_type_codes),
    ]
