# Generated by Django 4.2.29 on 2026-05-09 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_accreditationproject_client_profile'),
        ('indicators', '0003_indicator_ai_assistance_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_category', models.CharField(choices=[('DOCUMENT_POLICY', 'Document / Policy'), ('RECORD_REGISTER', 'Record / Register'), ('PHYSICAL_FACILITY', 'Physical / Facility'), ('LICENSE_CERTIFICATE', 'License / Certificate'), ('STAFF_TRAINING', 'Staff / Training'), ('PROCESS_WORKFLOW', 'Process / Workflow'), ('AUDIT_QUALITY', 'Audit / Quality'), ('MIXED_EVIDENCE', 'Mixed Evidence'), ('MANUAL_REVIEW', 'Manual Review Needed')], default='MANUAL_REVIEW', max_length=32)),
                ('artifact_type', models.CharField(blank=True, max_length=100)),
                ('mandatory', models.BooleanField(default=True)),
                ('ai_generatable', models.BooleanField(default=False)),
                ('physical_proof_required', models.BooleanField(default=False)),
                ('signature_required', models.BooleanField(default=False)),
                ('ongoing_record_required', models.BooleanField(default=False)),
                ('default_document_type', models.CharField(blank=True, choices=[('SOP', 'SOP'), ('POLICY', 'Policy'), ('FORM', 'Form'), ('MINUTES', 'Minutes'), ('REPORT', 'Report'), ('OTHER', 'Other')], default='', max_length=20)),
                ('primary_action_required', models.CharField(blank=True, choices=[('GENERATE_DOCUMENT', 'Generate Document'), ('COLLECT_RECORD', 'Collect Record'), ('UPLOAD_PHOTO', 'Upload Photo'), ('ARRANGE_PHYSICAL_COMPLIANCE', 'Arrange Physical Compliance'), ('OBTAIN_CERTIFICATE', 'Obtain Certificate'), ('TRAIN_STAFF', 'Train Staff'), ('MAINTAIN_LOG', 'Maintain Log'), ('REVIEW_EXISTING_EVIDENCE', 'Review Existing Evidence'), ('MANUAL_DECISION', 'Manual Decision')], default='', max_length=40)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_requirements', to='indicators.indicator')),
            ],
            options={
                'ordering': ['indicator__sort_order', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvidenceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MISSING', 'Missing'), ('PARTIAL', 'Partial'), ('COMPLETE', 'Complete'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_APPLICABLE', 'Not Applicable')], default='MISSING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('gap_summary', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_evidence_requirements', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_evidence_requirements', to=settings.AUTH_USER_MODEL)),
                ('evidence_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_fulfillments', to='indicators.evidencerequirement')),
                ('framework_indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_evidence_requirements', to='indicators.indicator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_evidence_requirements', to='projects.accreditationproject')),
                ('project_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_evidence_requirements', to='indicators.projectindicator')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_project_evidence_requirements', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_project_evidence_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project__name', 'project_indicator__indicator__area__sort_order', 'project_indicator__indicator__standard__sort_order', 'project_indicator__indicator__sort_order', 'evidence_requirement__display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectevidencerequirement',
            constraint=models.UniqueConstraint(fields=('project_indicator', 'evidence_requirement'), name='unique_project_indicator_evidence_requirement'),
        ),
    ]
