# Generated by Django 5.2.14 on 2026-05-09 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0003_indicator_ai_assistance_level_and_more"),
        ("projects", "0002_accreditationproject_client_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "evidence_category",
                    models.CharField(
                        choices=[
                            ("AUDIT_QUALITY", "Audit Quality"),
                            ("DOCUMENT_POLICY", "Document Policy"),
                            ("LICENSE_CERTIFICATE", "License Certificate"),
                            ("MANUAL_REVIEW", "Manual Review"),
                            ("MIXED_EVIDENCE", "Mixed Evidence"),
                            ("PHYSICAL_FACILITY", "Physical Facility"),
                            ("PROCESS_WORKFLOW", "Process Workflow"),
                            ("RECORD_REGISTER", "Record Register"),
                            ("STAFF_TRAINING", "Staff Training"),
                        ],
                        default="DOCUMENT_POLICY",
                        max_length=50,
                    ),
                ),
                ("mandatory", models.BooleanField(default=True)),
                ("ai_generatable", models.BooleanField(default=False)),
                ("physical_proof_required", models.BooleanField(default=False)),
                ("signature_required", models.BooleanField(default=False)),
                ("ongoing_record_required", models.BooleanField(default=False)),
                (
                    "default_document_type",
                    models.CharField(
                        choices=[
                            ("SOP", "SOP"),
                            ("POLICY", "Policy"),
                            ("FORM", "Form"),
                            ("MINUTES", "Minutes"),
                            ("REPORT", "Report"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "primary_action_required",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GENERATE_DOCUMENT", "Generate Document"),
                            ("COLLECT_RECORD", "Collect Record"),
                            ("UPLOAD_PHOTO", "Upload Photo"),
                            (
                                "ARRANGE_PHYSICAL_COMPLIANCE",
                                "Arrange Physical Compliance",
                            ),
                            ("OBTAIN_CERTIFICATE", "Obtain Certificate"),
                            ("TRAIN_STAFF", "Train Staff"),
                            ("MAINTAIN_LOG", "Maintain Log"),
                            ("REVIEW_EXISTING_EVIDENCE", "Review Existing Evidence"),
                            ("MANUAL_DECISION", "Manual Decision"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "framework_indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_requirements",
                        to="indicators.indicator",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectEvidenceRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MISSING", "Missing"),
                            ("PARTIAL", "Partial"),
                            ("COMPLETE", "Complete"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("NOT_APPLICABLE", "Not Applicable"),
                        ],
                        default="MISSING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("gap_summary", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_evidence_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="indicators.evidencerequirement",
                    ),
                ),
                (
                    "framework_indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="indicators.indicator",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_evidence_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_requirements",
                        to="projects.accreditationproject",
                    ),
                ),
                (
                    "project_indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_requirements",
                        to="indicators.projectindicator",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_evidence_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project_indicator", "evidence_requirement")},
            },
        ),
    ]
