# Generated by Django 5.2.12 on 2026-05-11 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_evidencerequirement_projectevidencerequirement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRequirementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_category', models.CharField(choices=[('DOCUMENT_POLICY', 'Document / Policy'), ('RECORD_REGISTER', 'Record / Register'), ('PHYSICAL_FACILITY', 'Physical / Facility'), ('LICENSE_CERTIFICATE', 'License / Certificate'), ('STAFF_TRAINING', 'Staff / Training'), ('PROCESS_WORKFLOW', 'Process / Workflow'), ('AUDIT_QUALITY', 'Audit / Quality'), ('MIXED_EVIDENCE', 'Mixed Evidence'), ('MANUAL_REVIEW', 'Manual Review Needed')], default='MANUAL_REVIEW', max_length=32)),
                ('artifact_type', models.CharField(blank=True, max_length=100)),
                ('mandatory', models.BooleanField(default=True)),
                ('ai_generatable', models.BooleanField(default=False)),
                ('physical_proof_required', models.BooleanField(default=False)),
                ('signature_required', models.BooleanField(default=False)),
                ('ongoing_record_required', models.BooleanField(default=False)),
                ('default_document_type', models.CharField(blank=True, choices=[('SOP', 'SOP'), ('POLICY', 'Policy'), ('FORM', 'Form'), ('MINUTES', 'Minutes'), ('REPORT', 'Report'), ('OTHER', 'Other')], default='', max_length=20)),
                ('primary_action_required', models.CharField(blank=True, choices=[('GENERATE_DOCUMENT', 'Generate Document'), ('COLLECT_RECORD', 'Collect Record'), ('UPLOAD_PHOTO', 'Upload Photo'), ('ARRANGE_PHYSICAL_COMPLIANCE', 'Arrange Physical Compliance'), ('OBTAIN_CERTIFICATE', 'Obtain Certificate'), ('TRAIN_STAFF', 'Train Staff'), ('MAINTAIN_LOG', 'Maintain Log'), ('REVIEW_EXISTING_EVIDENCE', 'Review Existing Evidence'), ('MANUAL_DECISION', 'Manual Decision')], default='', max_length=40)),
                ('review_status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggested_requirements', to='indicators.indicator')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_evidence_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence Requirement Suggestion',
                'verbose_name_plural': 'Evidence Requirement Suggestions',
                'ordering': ['indicator__sort_order', 'title'],
            },
        ),
    ]
