# Generated by Django 4.2.29 on 2026-04-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationproject',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.clientprofile'),
        ),
    ]
