[pytest]
DJANGO_SETTINGS_MODULE = config.accrediops_backend.settings
python_files = test_*.py *_test.py
addopts = --reuse-db --cov=apps --cov-report=term-missing --cov-report=xml:coverage.xml --cov-report=html:htmlcov
testpaths = apps
