// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/audit" | "/admin/client-profiles" | "/admin/frameworks" | "/admin/frameworks/classification" | "/admin/import-logs" | "/admin/masters/document-types" | "/admin/masters/evidence-types" | "/admin/masters/priorities" | "/admin/masters/statuses" | "/admin/overrides" | "/admin/system-health" | "/admin/users" | "/frameworks/[id]/analysis" | "/login" | "/project-indicators/[id]" | "/projects" | "/projects/[projectId]" | "/projects/[projectId]/areas-progress" | "/projects/[projectId]/client-profile" | "/projects/[projectId]/exports" | "/projects/[projectId]/inspection" | "/projects/[projectId]/pending-actions" | "/projects/[projectId]/print-pack" | "/projects/[projectId]/readiness" | "/projects/[projectId]/recurring" | "/projects/[projectId]/standards-progress" | "/projects/[projectId]/worklist"
type AppRouteHandlerRoutes = "/healthz"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]" | "/api/[[...path]]/"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/audit": {}
  "/admin/client-profiles": {}
  "/admin/frameworks": {}
  "/admin/frameworks/classification": {}
  "/admin/import-logs": {}
  "/admin/masters/document-types": {}
  "/admin/masters/evidence-types": {}
  "/admin/masters/priorities": {}
  "/admin/masters/statuses": {}
  "/admin/overrides": {}
  "/admin/system-health": {}
  "/admin/users": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/api/[[...path]]/": { "path"?: string[]; }
  "/frameworks/[id]/analysis": { "id": string; }
  "/healthz": {}
  "/login": {}
  "/project-indicators/[id]": { "id": string; }
  "/projects": {}
  "/projects/[projectId]": { "projectId": string; }
  "/projects/[projectId]/areas-progress": { "projectId": string; }
  "/projects/[projectId]/client-profile": { "projectId": string; }
  "/projects/[projectId]/exports": { "projectId": string; }
  "/projects/[projectId]/inspection": { "projectId": string; }
  "/projects/[projectId]/pending-actions": { "projectId": string; }
  "/projects/[projectId]/print-pack": { "projectId": string; }
  "/projects/[projectId]/readiness": { "projectId": string; }
  "/projects/[projectId]/recurring": { "projectId": string; }
  "/projects/[projectId]/standards-progress": { "projectId": string; }
  "/projects/[projectId]/worklist": { "projectId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
