// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(workbench)/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/client-profiles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/client-profiles">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/client-profiles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/frameworks/classification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/frameworks/classification">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/frameworks/classification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/frameworks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/frameworks">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/frameworks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/import-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/import-logs">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/import-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/masters/document-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/masters/document-types">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/masters/document-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/masters/evidence-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/masters/evidence-types">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/masters/evidence-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/masters/priorities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/masters/priorities">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/masters/priorities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/masters/statuses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/masters/statuses">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/masters/statuses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/overrides/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/overrides">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/overrides/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/system-health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system-health">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/system-health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/frameworks/[id]/analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/frameworks/[id]/analysis">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/frameworks/[id]/analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/project-indicators/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-indicators/[id]">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/project-indicators/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/[projectId]/areas-progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/areas-progress">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/[projectId]/areas-progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/[projectId]/client-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/client-profile">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/[projectId]/client-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/[projectId]/exports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/exports">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/[projectId]/exports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/[projectId]/inspection/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/inspection">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/[projectId]/inspection/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/[projectId]/pending-actions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/pending-actions">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/[projectId]/pending-actions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/[projectId]/print-pack/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/print-pack">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/[projectId]/print-pack/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/[projectId]/readiness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/readiness">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/[projectId]/readiness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/[projectId]/recurring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/recurring">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/[projectId]/recurring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/[projectId]/standards-progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/standards-progress">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/[projectId]/standards-progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/[projectId]/worklist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/worklist">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/[projectId]/worklist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/healthz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/healthz">> = Specific
  const handler = {} as typeof import("../../app/healthz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(workbench)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workbench)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(workbench)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
