# Generated by Django 4.2.29 on 2026-04-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0002_indicator_evidence_reuse_policy_and_more'),
        ('evidence', '0002_evidenceitem_file_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('evidence_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_pack_items', to='evidence.evidenceitem')),
                ('project_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_pack_items', to='indicators.projectindicator')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
