import { expect, test } from "@playwright/test";
import { loginAsSeededAdmin } from "./helpers";

test.describe("Inspection Pack UI", () => {
  test("renders the inspection pack preview with mock data", async ({ page }) => {
    await loginAsSeededAdmin(page);

    // Navigate to a project's detail page first to get the projectId
    await page.getByRole("link", { name: "Open project" }).first().click();
    await expect(page).toHaveURL(/\/projects\/\d+/);
    const projectId = Number(page.url().match(/\/projects\/(\d+)/)?.[1]);
    expect(projectId).toBeGreaterThan(0);

    // Navigate to the Inspection Pack page
    await page.goto(`/projects/${projectId}/print-pack`);
    await expect(page).toHaveURL(/\/projects\/\d+\/print-pack/);

    // Verify presence of PageHeader elements
    await expect(page.getByRole("heading", { name: "Inspection Pack Preview" })).toBeVisible();
    await expect(page.getByText("Structured inspection pack with area → standard → indicator → evidence ordering.")).toBeVisible();
    await expect(page.getByRole("button", { name: "Print" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Generate Inspection Pack" })).toBeVisible();

    // Verify Project Summary section
    await expect(page.getByRole("heading", { name: "Project Summary" })).toBeVisible();
    await expect(page.getByText("Client Alpha Health System")).toBeVisible();
    await expect(page.getByText("Hospital Accreditation")).toBeVisible();
    await expect(page.getByText("85% Ready")).toBeVisible();
    await expect(page.getByText("Total: 30 • Met: 25 • Partial: 3 • Missing: 2")).toBeVisible();

    // Verify AI Disclaimer
    await expect(page.getByText("AI Advisory Disclaimer:")).toBeVisible();
    await expect(page.getByText("This inspection pack may contain AI-assisted drafts.")).toBeVisible();

    // Verify a section and its content
    await expect(page.getByRole("heading", { name: "Area A: Patient Safety" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Standard 1: Medication Management" })).toBeVisible();

    // Verify an indicator's details
    await expect(page.getByText("PS-001 — MET — Risk: LOW")).toBeVisible();
    await expect(page.getByText("All medications are stored securely and correctly.")).toBeVisible();
    await expect(page.getByText("Owner: John Smith")).toBeVisible();
    await expect(page.getByText("Reviewer: Dr. Emily White")).toBeVisible();
    await expect(page.getByText("Approver: Dr. Alex Green")).toBeVisible();

    // Verify linked evidence
    await expect(page.getByText("#1 Medication Storage Policy V2.0 [APPROVED] • MED-POL-001 • DIGITAL (SharePoint/Policies/Medication)")).toBeVisible();
    await expect(page.getByText("Reviewed by Dr. Emily White")).toBeVisible();

    // Verify AI Drafts (Advisory)
    await expect(page.getByText("AI Drafts (Advisory, Review Required):")).toBeVisible();
    await expect(page.getByText("AI Draft Draft Procedure: Medication Storage Check [HUMAN_REVIEW_REQUIRED] • Generated by AI Assistant")).toBeVisible();

    // Verify Promoted AI Drafts
    await expect(page.getByText("Promoted AI Drafts (Linked to Evidence):")).toBeVisible();
    await expect(page.getByText("Promoted AI Draft Promoted Draft: Reconciliation Procedure • Linked to Evidence ID: 1003")).toBeVisible();

    // Verify Consolidated Lists
    await expect(page.getByRole("heading", { name: "Consolidated Lists" })).toBeVisible();
    await expect(page.getByText("Missing Evidence:")).toBeVisible();
    await expect(page.getByText("Missing Indicator SQ-001 - 1 item(s) missing.")).toBeVisible();
    await expect(page.getByText("Partial/Unapproved Evidence:")).toBeVisible();
    await expect(page.getByText("Partial Indicator PS-002 - 1 item(s) unapproved.")).toBeVisible();
    await expect(page.getByText("AI Drafts Requiring Review:")).toBeVisible();
    await expect(page.getByText("AI Draft Indicator PS-001 - Draft Procedure: Medication Storage Check [HUMAN_REVIEW_REQUIRED]")).toBeVisible();
  });
});
