# Generated by Django 4.2.29 on 2026-04-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('mode', models.CharField(choices=[('DIGITAL', 'Digital'), ('UPLOAD', 'Upload'), ('EITHER', 'Either')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True)),
                ('expected_title_template', models.CharField(blank=True, max_length=255)),
                ('project_indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_requirement', to='indicators.projectindicator')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringEvidenceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('period_label', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('MISSED', 'Missed')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('linked_evidence_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='evidence.evidenceitem')),
                ('recurring_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='recurring.recurringrequirement')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='recurringevidenceinstance',
            constraint=models.UniqueConstraint(fields=('recurring_requirement', 'due_date'), name='unique_recurring_due_date_per_requirement'),
        ),
    ]
