# Generated by Django 4.2.29 on 2026-04-02 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('UPLOAD', 'Upload'), ('URL', 'URL'), ('TEXT_NOTE', 'Text Note'), ('GENERATED', 'Generated'), ('EXTERNAL_REF', 'External Reference')], max_length=20)),
                ('file_or_url', models.CharField(blank=True, max_length=500)),
                ('text_content', models.TextField(blank=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('evidence_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('validity_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='UNKNOWN', max_length=20)),
                ('completeness_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete')], default='UNKNOWN', max_length=20)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('project_indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='indicators.projectindicator')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidence_items', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
