# Generated by Django 4.2.29 on 2026-04-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceitem',
            name='file_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='is_physical_copy_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='location_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='physical_location_type',
            field=models.CharField(blank=True, choices=[('BINDER', 'Binder'), ('CABINET', 'Cabinet'), ('ROOM', 'Room'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
