# Generated by Django 5.2.14 on 2026-05-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0002_evidenceitem_file_label_and_more"),
        ("indicators", "0004_evidencerequirement_projectevidencerequirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidenceitem",
            name="evidence_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="indicators.evidencerequirement",
            ),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="project_evidence_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="indicators.projectevidencerequirement",
            ),
        ),
    ]
