# Generated by Django 4.2.29 on 2026-05-09 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_evidencerequirement_projectevidencerequirement_and_more'),
        ('evidence', '0002_evidenceitem_file_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceitem',
            name='project_evidence_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='indicators.projectevidencerequirement'),
        ),
    ]
