# Generated by Django 4.2.29 on 2026-04-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=120)),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('department_names', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['organization_name', 'id'],
            },
        ),
    ]
