# Generated by Django 4.2.29 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_clientprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="linked_users",
            field=models.ManyToManyField(blank=True, related_name="client_profiles", to="accounts.user"),
        ),
    ]
