export const queryKeys = {
  projects: ["projects"] as const,
  adminDashboard: ["admin", "dashboard"] as const,
  adminMasters: (key: string) => ["admin", "masters", key] as const,
  adminUsers: ["admin", "users"] as const,
  audit: <T extends object>(filters: T) => ["audit", filters] as const,
  overrides: ["admin", "overrides"] as const,
  projectReadiness: (projectId: number | string) => ["projects", projectId, "readiness"] as const,
  inspection: (projectId: number | string) => ["projects", projectId, "inspection-view"] as const,
  preInspection: (projectId: number | string) => ["projects", projectId, "pre-inspection-check"] as const,
  exportHistory: (projectId: number | string) => ["projects", projectId, "exports", "history"] as const,
  importLogs: ["admin", "import-logs"] as const,
  frameworks: ["frameworks"] as const,
  frameworkAnalysis: (frameworkId: number | string) => ["frameworks", frameworkId, "analysis"] as const,
  project: (projectId: number | string) => ["projects", projectId] as const,
  worklist: <T extends object>(filters: T) => ["worklist", filters] as const,
  indicator: (indicatorId: number | string) => ["project-indicators", indicatorId] as const,
  evidence: (indicatorId: number | string) => ["project-indicators", indicatorId, "evidence"] as const,
  recurringQueue: <T extends object>(filters: T) => ["recurring-queue", filters] as const,
  standardsProgress: (projectId: number | string) => ["projects", projectId, "standards-progress"] as const,
  areasProgress: (projectId: number | string) => ["projects", projectId, "areas-progress"] as const,
  aiOutputs: (indicatorId: number | string) => ["project-indicators", indicatorId, "ai-outputs"] as const,
};
