from datetime import timedelta

from django.utils import timezone

from apps.api.tests.base import ContractBaseTestCase
from apps.masters.choices import RecurringInstanceStatusChoices
from apps.projects.services import project_summary_counts
from apps.recurring.models import RecurringEvidenceInstance


class ProjectSummaryCountsTest(ContractBaseTestCase):
    def setUp(self):
        super().setUp()
        # Initialize the project using the helper from ContractBaseTestCase
        # This will create project indicators and recurring requirements
        self.initialize_project()

        # At this point, the base class initialization creates ProjectIndicators
        # based on indicators in the framework. Let's get the active recurring
        # requirement to set up test scenarios for instances.

        from apps.recurring.models import RecurringRequirement
        # Let's find the recurring requirement created
        self.recurring_requirement = RecurringRequirement.objects.filter(
            project_indicator__project=self.project
        ).first()

        # Clear any instances generated by initialization to have a clean state for these tests
        RecurringEvidenceInstance.objects.all().delete()

    def test_project_summary_counts_initial_state(self):
        counts = project_summary_counts(self.project)

        # We know from ContractBaseTestCase that there are 2 indicators
        # (IND-001 and IND-002) in the framework
        self.assertEqual(counts["total_indicators"], 2)
        self.assertEqual(counts["met_indicators"], 0)
        self.assertEqual(counts["pending_indicators"], 2)
        self.assertEqual(counts["recurring_due_today"], 0)
        self.assertEqual(counts["overdue_recurring_items"], 0)

    def test_project_summary_counts_with_met_indicators(self):
        # Update one project indicator to met (use update() to avoid model validation error on save())
        project_indicator = self.project.project_indicators.first()
        self.project.project_indicators.filter(pk=project_indicator.pk).update(is_met=True)

        counts = project_summary_counts(self.project)
        self.assertEqual(counts["total_indicators"], 2)
        self.assertEqual(counts["met_indicators"], 1)
        self.assertEqual(counts["pending_indicators"], 1)

    def test_project_summary_counts_recurring_due_today(self):
        today = timezone.localdate()

        # Create an instance due today with PENDING status
        RecurringEvidenceInstance.objects.create(
            recurring_requirement=self.recurring_requirement,
            due_date=today,
            period_label="Today",
            status=RecurringInstanceStatusChoices.PENDING,
        )

        # We can reuse the same requirement for another day if needed, but for "due today",
        # let's just create one instance due today, and another one tomorrow (approved),
        # but change the period_label and due_date appropriately to avoid unique constraints
        # Actually, if we just want to test if APPROVED is counted, we can create an instance
        # due today that is APPROVED. But wait, it must have a unique due_date.
        # So instead of testing due_today with APPROVED on the same day as PENDING,
        # we can just test them on different dates. Wait, if it's not due today, it won't be counted anyway.
        # Let's delete the existing instances first, and we can just have one DUE today that is APPROVED.
        # But wait, we want to test that PENDING is counted and APPROVED is not.

        # We'll create another indicator and its requirement
        from apps.indicators.models import Indicator, ProjectIndicator
        from apps.recurring.models import RecurringRequirement

        ind3 = Indicator.objects.create(
            framework=self.framework, area=self.area, standard=self.standard,
            code="IND-003", text="Test", evidence_type="DOCUMENT", is_recurring=True,
            recurrence_frequency="DAILY"
        )
        pi3 = ProjectIndicator.objects.create(
            project=self.project, indicator=ind3, priority="MEDIUM", due_date=today
        )
        req3 = RecurringRequirement.objects.create(
            project_indicator=pi3, frequency="DAILY", mode="MANUAL", start_date=today, is_active=True
        )

        RecurringEvidenceInstance.objects.create(
            recurring_requirement=req3,
            due_date=today,
            period_label="Today Approved",
            status=RecurringInstanceStatusChoices.APPROVED,
        )

        counts = project_summary_counts(self.project)
        self.assertEqual(counts["recurring_due_today"], 1)
        self.assertEqual(counts["overdue_recurring_items"], 0)

    def test_project_summary_counts_overdue_recurring_items(self):
        today = timezone.localdate()
        yesterday = today - timedelta(days=1)

        from apps.indicators.models import Indicator, ProjectIndicator
        from apps.recurring.models import RecurringRequirement

        ind2 = Indicator.objects.create(
            framework=self.framework, area=self.area, standard=self.standard,
            code="IND-002-TEST", text="Test", evidence_type="DOCUMENT", is_recurring=True,
            recurrence_frequency="DAILY"
        )
        pi2 = ProjectIndicator.objects.create(
            project=self.project, indicator=ind2, priority="MEDIUM", due_date=today
        )
        req2 = RecurringRequirement.objects.create(
            project_indicator=pi2, frequency="DAILY", mode="MANUAL", start_date=today, is_active=True
        )

        ind3 = Indicator.objects.create(
            framework=self.framework, area=self.area, standard=self.standard,
            code="IND-003-TEST", text="Test", evidence_type="DOCUMENT", is_recurring=True,
            recurrence_frequency="DAILY"
        )
        pi3 = ProjectIndicator.objects.create(
            project=self.project, indicator=ind3, priority="MEDIUM", due_date=today
        )
        req3 = RecurringRequirement.objects.create(
            project_indicator=pi3, frequency="DAILY", mode="MANUAL", start_date=today, is_active=True
        )

        # Create an overdue instance with SUBMITTED status (still considered actionable/overdue)
        RecurringEvidenceInstance.objects.create(
            recurring_requirement=self.recurring_requirement,
            due_date=yesterday,
            period_label="Yesterday",
            status=RecurringInstanceStatusChoices.SUBMITTED,
        )

        # Create an overdue instance with MISSED status
        RecurringEvidenceInstance.objects.create(
            recurring_requirement=req2,
            due_date=yesterday - timedelta(days=1),
            period_label="Older",
            status=RecurringInstanceStatusChoices.MISSED,
        )

        # Create an overdue instance with APPROVED status (should not be counted)
        RecurringEvidenceInstance.objects.create(
            recurring_requirement=req3,
            due_date=yesterday,
            period_label="Yesterday Approved",
            status=RecurringInstanceStatusChoices.APPROVED,
        )

        counts = project_summary_counts(self.project)
        self.assertEqual(counts["recurring_due_today"], 0)
        self.assertEqual(counts["overdue_recurring_items"], 2)

    def test_project_summary_counts_combined(self):
        today = timezone.localdate()
        yesterday = today - timedelta(days=1)

        # Set all indicators to met (use update() to avoid model validation error on save())
        self.project.project_indicators.all().update(is_met=True)

        # Due today, PENDING
        RecurringEvidenceInstance.objects.create(
            recurring_requirement=self.recurring_requirement,
            due_date=today,
            period_label="Today",
            status=RecurringInstanceStatusChoices.PENDING,
        )

        # Overdue, MISSED
        RecurringEvidenceInstance.objects.create(
            recurring_requirement=self.recurring_requirement,
            due_date=yesterday,
            period_label="Yesterday",
            status=RecurringInstanceStatusChoices.MISSED,
        )

        counts = project_summary_counts(self.project)
        self.assertEqual(counts["total_indicators"], 2)
        self.assertEqual(counts["met_indicators"], 2)
        self.assertEqual(counts["pending_indicators"], 0)
        self.assertEqual(counts["recurring_due_today"], 1)
        self.assertEqual(counts["overdue_recurring_items"], 1)
from django.core.exceptions import PermissionDenied

from apps.api.tests.base import ContractBaseTestCase
from apps.audit.models.audit_event import AuditEvent
from apps.projects.models import AccreditationProject
from apps.projects.services import delete_project


class DeleteProjectServiceTests(ContractBaseTestCase):
    def test_delete_project_success_admin(self):
        project_id = self.project.id
        delete_project(project=self.project, actor=self.admin)

        # Verify project is deleted
        with self.assertRaises(AccreditationProject.DoesNotExist):
            AccreditationProject.objects.get(id=project_id)

        # Verify audit event
        audit_event = AuditEvent.objects.filter(
            event_type="project.deleted", object_id=str(project_id)
        ).first()
        self.assertIsNotNone(audit_event)
        self.assertEqual(audit_event.actor, self.admin)
        self.assertIsNotNone(audit_event.before_json)
        self.assertIsNone(audit_event.after_json)

    def test_delete_project_success_lead(self):
        project_id = self.project.id
        delete_project(project=self.project, actor=self.lead)

        # Verify project is deleted
        with self.assertRaises(AccreditationProject.DoesNotExist):
            AccreditationProject.objects.get(id=project_id)

        # Verify audit event
        audit_event = AuditEvent.objects.filter(
            event_type="project.deleted", object_id=str(project_id)
        ).first()
        self.assertIsNotNone(audit_event)
        self.assertEqual(audit_event.actor, self.lead)

    def test_delete_project_permission_denied(self):
        project_id = self.project.id

        # OWNER, REVIEWER, APPROVER should not have access
        for user in [self.owner, self.reviewer, self.approver]:
            with self.assertRaises(PermissionDenied):
                delete_project(project=self.project, actor=user)

            # Verify project is not deleted
            self.assertTrue(AccreditationProject.objects.filter(id=project_id).exists())

            # Verify no audit event is logged
            self.assertFalse(
                AuditEvent.objects.filter(
                    event_type="project.deleted", actor=user, object_id=str(project_id)
                ).exists()
            )
